# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

executors:
  emscripten-executor:
    docker:
      - image: emscripten/emsdk:2.0.30

jobs:
  build-web:
    executor: emscripten-executor
    steps:
      - checkout
      - run: git submodule update --recursive --init
      - run: |
          mkdir build_web
          cd build_web
          emcmake cmake ../
          make deploy
      - persist_to_workspace:
          root: build_web
          paths:
            - deploy

workflows:
  build-web-deploy:
    jobs:
      - build-web
      - gh-pages/deploy:
          attach-workspace: true
          workspace-root: build_web
          build-dir: build_web/deploy
          requires:
            - build-web
          ssh-fingerprints: 'a4:8c:85:7f:e5:78:d0:3d:b3:f4:9b:e1:bd:14:db:1b'
          filters:
            branches:
              only:
                - main
